version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/walkie_talkie
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/walkie_talkie
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
